//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Factura
    {
        public int ID { get; set; }
        public string Cedula { get; set; }
        public string ValoraPagarEnergia { get; set; }
        public string ValoraPagarAgua { get; set; }
        public string TotalFactura { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
    }
}
